[package]
name = "purs"
version = "0.1.0"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2018"

[dependencies]
openssl = { version = '0.10', features = ['vendored']}
ansi_term = "0.11"
clap = "2.33"
dirs = "2.0"
git2 = "0.8"
regex = "1.1.6"
tico = "1.0.0"
